### ISSUE TITLE
JWT_ACCESS_TOKEN_EXPIRES not working as expected

### ISSUE THREAD

**Issue by ben-mvi** [vimalloc/flask-jwt-simple#11]
I set the following in my config file:
JWT_ACCESS_TOKEN_EXPIRES = datetime.timedelta(seconds=5*60)
expecting the token to expire in 5 minutes 
but sadly this does not happen...
Im not sure exactly how long it takes to expire but I think its about an hour... but could be longer or shorter....
in production, I have it set to 24 hours...but sadly it expires much shorter than that...
I wish I could control exactly how long it takes to expire...
am I doing something wrong?

**Comment by vimalloc** [comment]
`JWT_ACCESS_TOKEN_EXPIRES` is part of `flask-jwt-extended`, not `flask-jwt-simple`. For this extension you are looking for `JWT_EXPIRES`. You can view the options here: https://flask-jwt-simple.readthedocs.io/en/latest/options.html

**Comment by ben-mvi** [comment]
Thanks, I originally switched from flask-jwt to flask-jwt-extended and when I did that, I had to switch that variable name..but then when I switched to flask-jwt-simple I didnt think I would have to change it again :) thank you very much.
