### ISSUE TITLE
how to add prefix like prefix="/api/v1"

### ISSUE THREAD

**Issue by Firues** [vimalloc/flask-jwt-simple#2]
Hello!
Dear vimalloc,
can i add prefix like prefix="/api/v1" to my flask-jwt-simple for all requests? (sorry for stupid question)
Thank u for all!

**Comment by vimalloc** [comment]
You can accomplish this with flask blueprints and the `url_prefix` argument (it is outside of the scope for this extension). You can read more about those flask options here: http://flask.pocoo.org/docs/0.12/blueprints/#registering-blueprints
