### ISSUE TITLE
Is there need for so many dependencies in requirements.txt?

### ISSUE THREAD

**Issue by idchlife** [vimalloc/flask-jwt-simple#4]
Hi! I’m relatively new to python and Flask, right now working with flask app that needs jwt auth.

I noticed something strange in requirements file, though.

Dependencies list is huge! Is this library really uses all of those deps?

overall, thanks for wonderful jwt extension for flask!

**Comment by vimalloc** [comment]
Those are all the requirements needing for developing the extension. The include the stuff for running unit tests, building the documentation, etc. The requirements for just using this extension is much lower, and can be seen here: https://github.com/vimalloc/flask-jwt-simple/blob/master/setup.py#L20-L23

**Comment by vimalloc** [comment]
It should also be noted that the packages in the requirements.txt file are a recursive list of requirements, ie they include all of the requirements needed by Flask, PyJWT, tox, etc.

**Comment by idchlife** [comment]
Oh, thank you for clarification!

Again, thanks for wonderful libraries (simple and extended) for flask! They help a lot since flask-jwt is outdated.
