### ISSUE TITLE
AWS Cognito 

### ISSUE THREAD

**Issue by SimplySeth** [vimalloc/flask-jwt-simple#5]
AWS Cognito gives me: 

- Access Token
- Identity Token
- Refresh Token

Can I just plug in the Access Token somewhere and make it work ? 

And by 'plug in' I mean auth to cognito (with `warrant` module ) and pass the token to  `flask-jwt-simple`

I'm trying to figure out how to make `flask-jwt-simple` work with `cognito`. 

Thanks.

**Comment by vimalloc** [comment]
I'm not sure what Cognito is, so I couldn't way for sure. If it provides you with a JWT then it shouldn't be hard at all to consume with this extension. You just need to set the algorithm and decode key in this extension to the correct values and everything should just work.
