### ISSUE TITLE
How to expire a token

### ISSUE THREAD

**Issue by michaelbukachi** [vimalloc/flask-jwt-simple#7]
How would I expire a token, for instance, within a logout endpoint?

**Comment by vimalloc** [comment]
You cannot expire a token once created, you would need to blacklist it on your backend. You can build that into application when using this extension, or utilize Flask JWT Extended (the sister extension of this one) which has blacklisting built it. See: https://flask-jwt-extended.readthedocs.io/en/latest/blacklist_and_token_revoking.html

**Comment by michaelbukachi** [comment]
Switched to Extended. Thanks
